version: "3.9"

services:
  backend-dev:
    build: ./backend
    container_name: "${CONTAINER_NAME}"
    restart: unless-stopped
    ports:
      - "${PORT}:8000"
    volumes:
      - ./data:/data
      - ./frontend:/app/frontend:ro
    env_file: .env
