version: "3.9"

services:
  backend-dev:
    build: ./backend
    container_name: liber-dev
    ports:
      - "9000:8000"
    volumes:
      - ./data-dev:/data
      - ./frontend:/app/frontend:ro
    env_file: .env.dev
